default:
  image: node:16.18

test-frontend:
  stage: test
  script:
    - cd frontend
    - npm install
    - npm test -- --coverage --watchAll=false
  artifacts:
    reports:
      coverage_report:
        path: coverage/lcov-report/index.html
    expire_in: "10 days"

test-backend:
  stage: test
  script:
    - cd backend
    - npm install
    - npm run test
  artifacts:
    reports:
      coverage_report:
        path: coverage/lcov-report/index.html
    expire_in: "10 days"