default:
  image: node:16.18-alpine

test-frontend:
  stage: test
  script:
    - cd frontend
    - npm install
    - npm test -- --coverage --watchAll=false
    - cat coverage/lcov-report/index.html

test-backend:
  stage: test
  script:
    - cd backend
    - npm install
    - npm run test
    - cat coverage/lcov-report/index.html